import SwiftUI

import KagisecureFFI

/// What a "create test login" approval shows (ADR-0048 §3): each website with its registrable
/// domain large above the full URL and the near-host and non-`https` flags, then the title, the
/// username, the purpose (labelled as the agent's words), how the password will be generated and
/// the agent's reason.
///
/// Metadata only. The password does not exist yet when this is on screen; it is generated inside
/// the vault transaction after the approval and goes nowhere but into the item.
struct TestLoginFactsBlock: View {
    let facts: TestLoginFactsView

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            ForEach(Array(facts.websites.enumerated()), id: \.offset) { _, site in
                website(site)
            }
            VStack(alignment: .leading, spacing: 6) {
                ApprovalSheet.row(
                    "Title", ApprovalSheet.safe(facts.title, limit: 120),
                    identifier: "ks.approval.testLogin.title")
                ApprovalSheet.row(
                    "Username", ApprovalSheet.safe(facts.username, limit: 120),
                    identifier: "ks.approval.testLogin.username")
                ApprovalSheet.row(
                    "Purpose, as written by the agent", ApprovalSheet.safe(facts.purpose, limit: 200),
                    identifier: "ks.approval.testLogin.purpose")
                ApprovalSheet.row(
                    "Password", Self.generatorSummary(facts),
                    identifier: "ks.approval.testLogin.generator")
                if let reason = facts.reason, !reason.isEmpty {
                    ApprovalSheet.row(
                        "Reason, as written by the agent", ApprovalSheet.safe(reason, limit: 200),
                        identifier: "ks.approval.testLogin.reason")
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    /// One website: the registrable domain large, the full origin under it, then the flags.
    private func website(_ site: TestLoginWebsiteView) -> some View {
        let origin = site.origin
        let parts = AgentFillSheetView.hostParts(origin)
        return VStack(alignment: .leading, spacing: 4) {
            Text(parts.emphasized)
                .font(.title2.weight(.semibold))
                .fixedSize(horizontal: false, vertical: true)
                .accessibilityIdentifier("ks.approval.testLogin.domain")
            (Text("\(ApprovalSheet.safe(origin.scheme, limit: 16))://")
                .foregroundStyle(origin.notEncrypted ? AnyShapeStyle(.red) : AnyShapeStyle(.secondary))
                + Text(parts.dimmed).foregroundStyle(.secondary)
                + Text(parts.emphasized).bold().underline()
                + Text(parts.port).bold())
                .font(.system(.callout, design: .monospaced))
                .textSelection(.enabled)
                .fixedSize(horizontal: false, vertical: true)
                .accessibilityLabel(AgentFillSheetView.siteText(origin))
                .accessibilityIdentifier("ks.approval.testLogin.site")
            if site.notHttps {
                Self.flag(
                    "Not encrypted. This test login would be saved for an http site.",
                    systemImage: "lock.open.fill", color: .red)
                    .accessibilityIdentifier("ks.approval.testLogin.notHttps")
            }
            if let near = site.nearItemTitle {
                Self.flag(
                    Self.nearHostText(near),
                    systemImage: "exclamationmark.triangle.fill", color: .orange)
                    .accessibilityIdentifier("ks.approval.testLogin.nearHost")
            }
            if let unicode = origin.unicodeHost {
                ApprovalSheet.row(
                    "Shown by the browser as", ApprovalSheet.safe(unicode, limit: 253),
                    identifier: "ks.approval.testLogin.unicodeHost")
            }
            if origin.mixedScript {
                Self.flag(
                    "This name mixes writing systems, or has a part that does not decode. That is how one site's name is made to look like another's.",
                    systemImage: "exclamationmark.triangle.fill", color: .red)
                    .accessibilityIdentifier("ks.approval.testLogin.mixedScript")
            }
        }
    }

    /// The near-host warning: the person already has a login on this registrable domain.
    static func nearHostText(_ title: String) -> String {
        String(localized: "You already have a login for this domain: “\(ApprovalSheet.safe(title))”. A test login here is a different account.")
    }

    static func generatorSummary(_ facts: TestLoginFactsView) -> String {
        String(localized: "Generated by kagisecure: \(ApprovalSheet.safe(facts.generator, limit: 80)). The agent never receives it.")
    }

    /// The registrable domain the sheet leads with; several websites read "a.com and 1 more".
    static func leadDomain(_ facts: TestLoginFactsView) -> String {
        guard let first = facts.websites.first else { return String(localized: "an unknown site") }
        let domain = AgentFillSheetView.hostParts(first.origin).emphasized
        let more = facts.websites.count - 1
        return more > 0 ? String(localized: "\(domain) and \(more) more") : domain
    }

    private static func flag(_ text: LocalizedStringKey, systemImage: String, color: Color) -> some View {
        Label {
            Text(text).fixedSize(horizontal: false, vertical: true)
        } icon: {
            Image(systemName: systemImage)
        }
        .font(.callout)
        .foregroundStyle(color)
        .padding(10)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(color.opacity(0.12), in: RoundedRectangle(cornerRadius: 8))
    }

    private static func flag(_ text: String, systemImage: String, color: Color) -> some View {
        flag(LocalizedStringKey(text), systemImage: systemImage, color: color)
    }
}
