#!/bin/bash
#
# Generate the app icon, Kagisecure.icns, from the artwork in apps/macos/Artwork/.
#
# apps/macos/Artwork/icon.svg is the mark (the same one kagisecure.com uses);
# apps/macos/Artwork/icon-1024.png is that mark rendered at 1024x1024 with the standard macOS
# inset, and is what this script reads. Rendering the SVG needs a browser engine, so the PNG is
# committed rather than produced here. Re-render it by hand only when the mark changes.
#
# A PNG at apps/macos/Kagisecure/Resources/icon-1024.png (gitignored) overrides the committed
# artwork, for trying out a variant locally. With neither present, the script falls back to
# drawing an SF Symbol placeholder so a fresh checkout still builds.
#
#   apps/macos/Scripts/make-icon.sh
#
# Output: apps/macos/Kagisecure/Resources/Kagisecure.icns (gitignored; regenerated by the build).

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
resources="${here}/../Kagisecure/Resources"
work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

mkdir -p "${resources}"
master="${resources}/icon-1024.png"

artwork="${here}/../Artwork/icon-1024.png"
if [[ ! -f "${master}" && -f "${artwork}" ]]; then
	master="${artwork}"
fi

if [[ -f "${master}" ]]; then
	echo "using the artwork at ${master}"
else
	echo "no artwork; drawing the SF Symbol placeholder"
	master="${work}/icon-1024.png"
	cat >"${work}/draw.swift" <<'SWIFT'
// Draw the placeholder icon: an SF Symbol on a rounded square, into a 1024x1024 PNG.
import AppKit

let side = 1024.0
// macOS icons are drawn inset inside their canvas; ~0.82 is what Apple's own template uses.
let plate = side * 0.82
let inset = (side - plate) / 2

let image = NSImage(size: NSSize(width: side, height: side))
image.lockFocus()
guard let context = NSGraphicsContext.current else { fatalError("no graphics context") }
context.imageInterpolation = .high

let plateRect = NSRect(x: inset, y: inset, width: plate, height: plate)
// The continuous-corner radius Apple uses for macOS app icons is about 22.4% of the plate.
let rounded = NSBezierPath(roundedRect: plateRect,
                           xRadius: plate * 0.224,
                           yRadius: plate * 0.224)

// A slate gradient, dark enough that a white glyph reads at 16pt in the menu bar.
let gradient = NSGradient(colors: [
    NSColor(srgbRed: 0.24, green: 0.29, blue: 0.38, alpha: 1),
    NSColor(srgbRed: 0.11, green: 0.14, blue: 0.20, alpha: 1),
])
gradient?.draw(in: rounded, angle: -90)

let configuration = NSImage.SymbolConfiguration(pointSize: plate * 0.52, weight: .semibold)
guard let symbol = NSImage(systemSymbolName: "key.horizontal.fill", accessibilityDescription: nil)?
    .withSymbolConfiguration(configuration) else {
    fatalError("the SF Symbol key.horizontal.fill is not available on this system")
}

let glyph = NSImage(size: symbol.size)
glyph.lockFocus()
NSColor.white.set()
NSRect(origin: .zero, size: symbol.size).fill(using: .sourceOver)
symbol.draw(at: .zero, from: .zero, operation: .destinationIn, fraction: 1)
glyph.unlockFocus()

let glyphRect = NSRect(x: (side - glyph.size.width) / 2,
                       y: (side - glyph.size.height) / 2,
                       width: glyph.size.width,
                       height: glyph.size.height)
glyph.draw(in: glyphRect, from: .zero, operation: .sourceOver, fraction: 1)
image.unlockFocus()

guard let tiff = image.tiffRepresentation,
      let bitmap = NSBitmapImageRep(data: tiff),
      let png = bitmap.representation(using: .png, properties: [:]) else {
    fatalError("could not encode the icon as PNG")
}
try png.write(to: URL(fileURLWithPath: CommandLine.arguments[1]))
SWIFT
	xcrun swift "${work}/draw.swift" "${master}"
fi

iconset="${work}/Kagisecure.iconset"
mkdir -p "${iconset}"

# The ten entries iconutil expects. Anything missing and Finder falls back to a blurry upscale.
for entry in "16 1" "16 2" "32 1" "32 2" "128 1" "128 2" "256 1" "256 2" "512 1" "512 2"; do
	read -r point scale <<<"${entry}"
	pixels=$((point * scale))
	suffix=""
	[[ "${scale}" == "2" ]] && suffix="@2x"
	sips --setProperty format png --resampleHeightWidth "${pixels}" "${pixels}" \
		"${master}" --out "${iconset}/icon_${point}x${point}${suffix}.png" >/dev/null
done

iconutil --convert icns "${iconset}" --output "${resources}/Kagisecure.icns"
echo "wrote ${resources}/Kagisecure.icns ($(du -h "${resources}/Kagisecure.icns" | cut -f1))"
