//! Agent test logins: logins kagisecure generates for an agent's test users, whose password the
//! agent never receives ([ADR-0048](../../../../docs/decisions/0048-agent-test-logins.md)).
//!
//! # Where this sits
//!
//! `create_test_login`, `list_test_logins` and `trash_test_logins` are served by [`crate::service`], which reads the
//! policy out of the test-login vault (`VaultMeta.purpose`, ADR-0048 §1) and writes the item in
//! one vault transaction. This module holds what that needs beyond the vault:
//!
//! * [`TestLoginBroker`] — process-wide, like the agent-fill broker: the per-agent create limit
//!   of §11, which must survive a reconnect and a vault lock, and the passive notices of §10 the
//!   app drains;
//! * [`origin_auto`] — §3's rule for where no sheet is needed;
//! * [`TestLoginPass`] — the one way a sealed item at an allowed origin reaches an agent fill's
//!   release without a person's grant (§7). Only [`TestLoginPass::for_fill`] makes one, and it
//!   checks the switch, the vault, the seal and the origin itself.
//!
//! Nothing here reads a secret: the password is generated by `kagisecure_core::generator` into a
//! `Secret` inside the service's transaction, sealed by `kagisecure_core`, and never opened on
//! this side. `crossing`'s scan test holds this module to that.

pub(crate) mod bind;
pub mod limits;

use std::collections::VecDeque;
use std::net::IpAddr;
use std::sync::{Mutex, MutexGuard};
use std::time::Instant;

use kagisecure_core::Vault;
use kagisecure_core::model::{Item, TestLoginPolicy};
use kagisecure_core::proto::VaultId;
use kagisecure_core::vault::test_login::TestLoginProvenance;
use kagisecure_extension_ipc::origin::{Origin, covering_website};
use kagisecure_ipc::protocol::{AgentFillField, TestLoginSummary, rfc3339};

use crate::extension::agent_fill::AgentFillClock;

pub use limits::{CREATE_WINDOW, CREATES_PER_WINDOW};

/// The most live (not trashed) items the test-login vault holds (ADR-0048 §11).
pub const MAX_LIVE_ITEMS: usize = 200;

/// The tag every test login carries.
pub const TAG_AGENT_TEST: &str = "agent-test";

/// The label of the public field a test login's purpose is stored in (ADR-0048 §6): public and
/// searchable, unlike notes, which are secret.
pub const PURPOSE_LABEL: &str = "purpose";

/// How many notices wait for the app before the oldest is dropped.
const NOTICE_SLOTS: usize = 32;

/// Audit `detail` tokens for test logins (ADR-0048 §10). A fixed vocabulary.
pub mod audit_detail {
    /// A test login was created with no sheet: every website passed §3.
    pub const TEST_LOGIN_CREATED_AUTOMATIC: &str = "TEST_LOGIN_CREATED (automatic)";
    /// A test login was created after the person approved it at the sheet.
    pub const TEST_LOGIN_CREATED_APPROVED: &str = "TEST_LOGIN_CREATED (approved)";
    /// A sealed test login was filled at an allowed origin with no sheet (§7).
    pub const TEST_LOGIN_FILL_AUTOMATIC: &str = "TEST_LOGIN_FILL (automatic)";
    /// A sealed test login's sign-up fill at an allowed origin with no sheet (§7).
    pub const TEST_LOGIN_FILL_AUTOMATIC_SIGN_UP: &str = "TEST_LOGIN_FILL (automatic, sign-up)";
    /// A create refused by the per-agent rate limit or the vault's cap (§11).
    pub const TEST_LOGIN_RATE_LIMITED: &str = "TEST_LOGIN_RATE_LIMITED";
    /// A create answered `exists`: a sealed test login already covered it, and nothing was
    /// written (§6).
    pub const TEST_LOGIN_EXISTS: &str = "TEST_LOGIN_EXISTS";
    /// `create_test_login`'s `bind` wrote bindings into an environment of the test-login vault.
    pub const TEST_LOGIN_BOUND: &str = "TEST_LOGIN_BOUND";
    /// `trash_test_logins` was refused: a matched login is saved for a website outside §3.
    pub const TEST_LOGINS_TRASH_REFUSED: &str = "TEST_LOGINS_TRASH_REFUSED";

    /// The detail of a `trash_test_logins` that moved `matched` logins to the trash (§10):
    /// `TEST_LOGINS_TRASHED matched=<n>`.
    #[must_use]
    pub fn test_logins_trashed(matched: usize) -> String {
        format!("TEST_LOGINS_TRASHED matched={matched}")
    }
}

/// Something the person hears about without being asked anything (ADR-0048 §10): a system
/// notification and a menu-bar entry, "N test logins created by agents". Metadata only.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TestLoginNotice {
    /// An agent created a test login.
    Created {
        /// The agent, as the audit log names it.
        agent: String,
        /// The title kagisecure composed.
        title: String,
        /// The username the agent chose.
        username: String,
        /// The websites it is saved for.
        websites: Vec<String>,
    },
}

/// The process-wide test-login state: create limits and notices (ADR-0048 §10, §11).
///
/// The app holds one for the life of the process and hands the same `Arc` to every agent it
/// starts, so neither a lock nor a reconnect resets an agent's count. The switch itself is not
/// here: it lives in the vault (§1).
#[derive(Default)]
pub struct TestLoginBroker {
    state: Mutex<State>,
    clock: AgentFillClock,
}

#[derive(Default)]
struct State {
    limits: limits::Limits,
    notices: VecDeque<TestLoginNotice>,
}

impl std::fmt::Debug for TestLoginBroker {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TestLoginBroker").finish_non_exhaustive()
    }
}

impl TestLoginBroker {
    /// A broker with no counts and no notices, on the real clock.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// A broker whose limits read `clock`, so a test can see ten minutes pass.
    #[must_use]
    pub fn with_clock_for_test(clock: AgentFillClock) -> Self {
        Self {
            state: Mutex::default(),
            clock,
        }
    }

    fn state(&self) -> MutexGuard<'_, State> {
        self.state.lock().unwrap_or_else(|e| e.into_inner())
    }

    /// Every notice queued since the last call, oldest first.
    pub fn take_notices(&self) -> Vec<TestLoginNotice> {
        self.state().notices.drain(..).collect()
    }

    /// Reserve one create for the agent keyed `key`: the instant it was reserved at, to hand
    /// back with [`Self::release`] if nothing is created, or `None` over the limit.
    pub(crate) fn reserve(&self, key: &str) -> Option<Instant> {
        let now = self.clock.now();
        self.state().limits.reserve(key, now).then_some(now)
    }

    /// Hand back a reservation that created nothing.
    pub(crate) fn release(&self, key: &str, at: Instant) {
        self.state().limits.release(key, at);
    }

    /// Queue a notice for the app.
    pub(crate) fn notice(&self, notice: TestLoginNotice) {
        let mut state = self.state();
        if state.notices.len() >= NOTICE_SLOTS {
            state.notices.pop_front();
        }
        state.notices.push_back(notice);
    }
}

/// Whether `origin` is one where test logins need no sheet (ADR-0048 §3): a loopback address,
/// `localhost`, a `*.localhost` or `*.test` name, or a registrable domain the person allowed.
///
/// Private LAN ranges and single-label hosts other than `localhost` are not on the list.
#[must_use]
pub fn origin_auto(policy: &TestLoginPolicy, origin: &Origin) -> bool {
    let host = origin.host().to_ascii_lowercase();
    if origin.is_ip_literal() {
        return host.parse::<IpAddr>().is_ok_and(|ip| ip.is_loopback());
    }
    if host == "localhost" || host.ends_with(".localhost") || host.ends_with(".test") {
        return true;
    }
    origin.registrable_domain().is_some_and(|domain| {
        policy
            .auto_domains
            .iter()
            .any(|allowed| allowed.eq_ignore_ascii_case(&domain))
    })
}

/// The registrable domain to add to the allowed list for what the person typed, or `None` when
/// it has none: an IP address, a single label such as `localhost`, or a public suffix itself.
#[must_use]
pub fn allowed_domain(input: &str) -> Option<String> {
    let origin = Origin::parse(input).ok()?;
    if origin.is_ip_literal() {
        return None;
    }
    origin.registrable_domain()
}

/// Whether a fill of these fields may use a test login's no-sheet path at all: a login's fields,
/// never a one-time code (a test login has none).
fn fill_fields_ok(fields: &[AgentFillField]) -> bool {
    !fields.is_empty()
        && fields.iter().all(|f| {
            matches!(
                f,
                AgentFillField::Username | AgentFillField::Password | AgentFillField::NewPassword
            )
        })
        && kagisecure_ipc::protocol::agent_fill_fields_ok(fields)
}

/// Permission for one agent fill of a sealed test login at an allowed origin, with nobody asked
/// (ADR-0048 §7) — what `crossing::Approved::from_test_login` takes instead of a person's grant.
///
/// Crate-private, fields private to this module, not `Clone`: only [`Self::for_fill`] makes one,
/// and it makes one only when every condition of §7 holds on the vault it is handed.
#[derive(Debug)]
pub(crate) struct TestLoginPass {
    item_id: String,
    origin: String,
    fields: Vec<String>,
}

impl TestLoginPass {
    /// The pass for filling `fields` of `item` at `origin`, if the switch is on, the item is a
    /// sealed test login in the test-login vault and `origin` passes [`origin_auto`].
    pub(crate) fn for_fill(
        vault: &Vault,
        item: &Item,
        origin: &Origin,
        fields: &[AgentFillField],
    ) -> Option<Self> {
        let (_, policy) = vault.test_login_policy()?;
        (policy.enabled
            && fill_fields_ok(fields)
            && vault.test_login_sealed(item)
            && origin_auto(policy, origin))
        .then(|| Self {
            item_id: item.id.to_string(),
            origin: origin.ascii_serialization(),
            fields: fields.iter().map(|f| f.as_str().to_owned()).collect(),
        })
    }

    /// The item it is for.
    pub(crate) fn item_id(&self) -> &str {
        &self.item_id
    }

    /// The origin it is for, ASCII-serialized.
    pub(crate) fn origin(&self) -> &str {
        &self.origin
    }

    /// The field names it covers.
    pub(crate) fn fields(&self) -> &[String] {
        &self.fields
    }
}

/// Whether the release of a fill approved by a test-login pass may still go ahead, inside the
/// release transaction: the item is still sealed, the switch still on and the origin still
/// allowed. An item edited, moved or a policy changed since the pass was issued is refused.
pub(crate) fn still_passes(vault: &Vault, item: &Item, origin: &str) -> bool {
    let Ok(origin) = Origin::parse(origin) else {
        return false;
    };
    vault.test_login_policy().is_some_and(|(_, policy)| {
        policy.enabled && vault.test_login_sealed(item) && origin_auto(policy, &origin)
    })
}

/// The tags a test login carries: `agent-test`, `app:<app>`, `purpose:<purpose>`, then the
/// agent's own, each once.
pub(crate) fn compose_tags(app: &str, purpose: &str, extra: &[String]) -> Vec<String> {
    let mut tags = vec![
        TAG_AGENT_TEST.to_owned(),
        format!("app:{app}"),
        format!("purpose:{purpose}"),
    ];
    for tag in extra {
        if !tags.contains(tag) {
            tags.push(tag.clone());
        }
    }
    tags
}

/// The title of the `n`th test login for `app` and `purpose`: `test: <app> / <purpose> #<n>`.
pub(crate) fn compose_title(app: &str, purpose: &str, n: usize) -> String {
    format!("test: {app} / {purpose} #{n}")
}

/// The number the next test login for `app` and `purpose` gets: one more than the test logins
/// for them the vault holds, trashed ones included, so a number is never reused.
pub(crate) fn next_number(vault: &Vault, test_vault: VaultId, app: &str, purpose: &str) -> usize {
    vault
        .items()
        .iter()
        .filter(|i| i.vault_id == test_vault)
        .filter_map(TestLoginProvenance::of)
        .filter(|p| p.app == app && p.purpose == purpose)
        .count()
        + 1
}

/// How many live (not trashed) items the test-login vault holds.
pub(crate) fn live_items(vault: &Vault, test_vault: VaultId) -> usize {
    vault
        .items()
        .iter()
        .filter(|i| i.vault_id == test_vault && !i.is_trashed())
        .count()
}

/// The sealed, live, agent-visible test logins, in creation order.
pub(crate) fn sealed_items(vault: &Vault) -> Vec<&Item> {
    let Some(test_vault) = vault.agent_test_vault() else {
        return Vec::new();
    };
    if !test_vault.agent_visible {
        return Vec::new();
    }
    let mut items: Vec<&Item> = vault
        .items()
        .iter()
        .filter(|i| i.vault_id == test_vault.id && !i.is_trashed() && i.agent_visible)
        .filter(|i| vault.test_login_sealed(i))
        .collect();
    items.sort_by_key(|i| i.created_at);
    items
}

/// The sealed, live test logins saved for a website covering `website` (when given) and carrying
/// exactly `tag` (when given), in creation order — what `list_test_logins` filters by, and what
/// `trash_test_logins` and `kagisecure test-logins trash` move to the trash.
#[must_use]
pub fn matching<'v>(
    vault: &'v Vault,
    website: Option<&Origin>,
    tag: Option<&str>,
) -> Vec<&'v Item> {
    sealed_items(vault)
        .into_iter()
        .filter(|item| {
            website.is_none_or(|w| {
                covering_website(&crate::extension::saved_websites(item), w).is_some()
            })
        })
        .filter(|item| tag.is_none_or(|t| item.tags.iter().any(|x| x == t)))
        .collect()
}

/// Whether every website `item` is saved for passes [`origin_auto`] — the condition under which
/// an agent may trash it with nobody asked (ADR-0048 §12). A website that does not parse as an
/// origin does not pass, nor does an item saved for no website at all.
#[must_use]
pub fn every_website_auto(policy: &TestLoginPolicy, item: &Item) -> bool {
    let websites = crate::extension::saved_websites(item);
    !websites.is_empty()
        && websites
            .iter()
            .all(|w| Origin::parse(w).is_ok_and(|origin| origin_auto(policy, &origin)))
}

/// The sealed test login with `username` that already covers every one of `websites`, if there
/// is one (ADR-0048 §6's `exists`).
pub(crate) fn existing<'v>(
    vault: &'v Vault,
    username: &str,
    websites: &[Origin],
) -> Option<&'v Item> {
    sealed_items(vault).into_iter().find(|item| {
        item.username() == Some(username)
            && websites.iter().all(|website| {
                covering_website(&crate::extension::saved_websites(item), website).is_some()
            })
    })
}

/// What `list_test_logins` says about `item`: metadata, the username, never the password.
#[must_use]
pub fn summary(item: &Item) -> TestLoginSummary {
    let purpose = item
        .fields
        .iter()
        .find(|f| f.label == PURPOSE_LABEL)
        .and_then(|f| f.value.as_public())
        .map(str::to_owned)
        .or_else(|| TestLoginProvenance::of(item).map(|p| p.purpose))
        .unwrap_or_default();
    TestLoginSummary {
        item_id: item.id,
        title: item.title.clone(),
        username: item.username().unwrap_or_default().to_owned(),
        websites: crate::extension::saved_websites(item),
        tags: item.tags.clone(),
        purpose,
        created_at: rfc3339(item.created_at),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn policy(domains: &[&str]) -> TestLoginPolicy {
        TestLoginPolicy {
            enabled: true,
            auto_domains: domains.iter().map(|d| (*d).to_owned()).collect(),
            ..TestLoginPolicy::default()
        }
    }

    fn auto(policy: &TestLoginPolicy, origin: &str) -> bool {
        origin_auto(policy, &Origin::parse(origin).unwrap())
    }

    #[test]
    fn loopback_localhost_and_reserved_names_need_no_sheet() {
        let p = policy(&[]);
        for origin in [
            "http://127.0.0.1:3000",
            "http://127.8.9.10",
            "http://[::1]:8080",
            "http://localhost:47800",
            "https://shop.localhost",
            "http://app.test:8000",
            "https://a.b.test",
        ] {
            assert!(auto(&p, origin), "{origin}");
        }
    }

    #[test]
    fn lan_single_labels_and_real_sites_do() {
        let p = policy(&[]);
        for origin in [
            "http://192.168.1.10",
            "http://10.0.0.2:3000",
            "http://[fe80::1]",
            "http://intranet",
            "https://example.com",
            "https://staging.example-partner.com",
            "https://localhost.example.com",
            "https://test.example.com",
        ] {
            assert!(!auto(&p, origin), "{origin}");
        }
    }

    #[test]
    fn an_allowed_domain_covers_its_subdomains_and_nothing_near_it() {
        let p = policy(&["example-partner.com"]);
        assert!(auto(&p, "https://staging.example-partner.com"));
        assert!(auto(&p, "https://example-partner.com:8443"));
        assert!(!auto(&p, "https://example-partner.com.evil.net"));
        assert!(!auto(&p, "https://examp1e-partner.com"));
    }

    #[test]
    fn only_a_registrable_domain_can_be_allowed() {
        assert_eq!(
            allowed_domain("https://staging.example-partner.com/login").as_deref(),
            Some("example-partner.com")
        );
        assert_eq!(
            allowed_domain("example.co.uk").as_deref(),
            Some("example.co.uk")
        );
        for refused in [
            "127.0.0.1",
            "http://[::1]",
            "localhost",
            "intranet",
            "co.uk",
            "github.io",
        ] {
            assert_eq!(allowed_domain(refused), None, "{refused}");
        }
    }

    #[test]
    fn titles_and_tags_are_composed_by_kagisecure() {
        assert_eq!(compose_title("shop", "buyer", 2), "test: shop / buyer #2");
        assert_eq!(
            compose_tags(
                "shop",
                "buyer",
                &["e2e".to_owned(), "agent-test".to_owned()]
            ),
            ["agent-test", "app:shop", "purpose:buyer", "e2e"]
        );
    }

    #[test]
    fn a_one_time_code_never_takes_the_test_login_path() {
        assert!(fill_fields_ok(&[
            AgentFillField::Username,
            AgentFillField::Password
        ]));
        assert!(fill_fields_ok(&[AgentFillField::Password]));
        assert!(!fill_fields_ok(&[AgentFillField::OneTimeCode]));
        assert!(!fill_fields_ok(&[]));
    }
}
