//! `cargo xtask bindgen-cs` — the C# declarations and the native library the Windows app loads.
//!
//! [ADR-0003](../../docs/decisions/0003-uniffi-vs-csbindgen.md) took its fallback: C# calls an
//! explicit `extern "C"` surface (`kagisecure-ffi`'s `capi` feature) through a P/Invoke layer in
//! `apps/windows/Kagisecure.Interop`, rather than bindings generated by `uniffi-bindgen-cs`. This
//! task does the two things a checkout needs for that layer:
//!
//! 1. **Generate** `Kagisecure.Interop/Native/NativeMethods.g.cs` from the `capi` sources with
//!    csbindgen: every `kgs_*` function, every `#[repr(C)]` struct they reach, every tag enum, and
//!    `KGS_ABI_VERSION`. The declarations are the part of the layer where a typo corrupts memory
//!    instead of failing to compile, so nobody types them. The output is checked in, for the
//!    reasons ADR-0009 gives for the Swift: it is the reviewable statement of what crosses, and a
//!    Visual Studio checkout opens without a Rust toolchain. The `tests` module fails when the
//!    checked-in file differs from what the sources generate, so a `capi` change without a
//!    regeneration is a test failure, not a corrupted stack.
//! 2. **Build** `kagisecure_ffi.dll` with `capi` on and stage it where the C# projects look for it.
//!    Windows only; the generation step runs anywhere.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::helpers::Profile;
use crate::util::{cargo, release_rustflags, run};

/// The library, as `[DllImport("kagisecure_ffi")]` names it.
const DLL: &str = "kagisecure_ffi.dll";

/// The `capi` sources csbindgen reads, relative to the repository root. `tests.rs` is left out:
/// it declares no C ABI.
const SOURCES: &[&str] = &[
    "crates/kagisecure-ffi/src/capi/mod.rs",
    "crates/kagisecure-ffi/src/capi/enums.rs",
    "crates/kagisecure-ffi/src/capi/items.rs",
    "crates/kagisecure-ffi/src/capi/session.rs",
    "crates/kagisecure-ffi/src/capi/presence.rs",
    "crates/kagisecure-ffi/src/capi/generate.rs",
    "crates/kagisecure-ffi/src/capi/agent.rs",
    "crates/kagisecure-ffi/src/capi/import.rs",
];

/// Where the generated declarations are checked in.
const GENERATED: &str = "apps/windows/Kagisecure.Interop/Native/NativeMethods.g.cs";

const HEADER: &str = "\
// Generated by `cargo xtask bindgen-cs` (csbindgen) from crates/kagisecure-ffi/src/capi/.
// Do not edit: change the Rust, regenerate, and commit both. xtask's
// `generated_csharp_is_up_to_date` test fails while the two disagree.
//
// Every function returns a KgsStatus (except kgs_abi_version and the *_free functions); every
// record and list it hands out goes back to exactly one *_free. The rules are in capi/mod.rs.";

/// Where the staged DLL goes: `target/windows/<Configuration>/`, named the way `dotnet` spells
/// `$(Configuration)` so `Kagisecure.Interop.csproj` can find it without being told the profile.
pub fn staging_dir(root: &Path, profile: Profile) -> PathBuf {
    root.join("target")
        .join("windows")
        .join(profile.configuration())
}

/// Regenerate the C# declarations, then build `kagisecure_ffi.dll` with the C ABI and stage it.
pub fn bindgen_cs(root: &Path, profile: Profile) -> Result<PathBuf> {
    let generated = root.join(GENERATED);
    generate(root, &generated)?;
    println!("bindgen-cs: C# declarations -> {}", generated.display());

    if !cfg!(windows) {
        bail!(
            "the C# declarations are regenerated; building {DLL} needs Windows, so run \
             cargo xtask bindgen-cs there for the DLL"
        );
    }
    // An explicit `--target`, even though it is the host, so the DLL lands in a directory only a
    // `capi` build writes to. `target/<profile>/kagisecure_ffi.dll` is also what a plain
    // `cargo build -p kagisecure-ffi` produces — without `capi`, and so without a single symbol
    // the C# side imports — and staging from there would race whichever build ran last.
    let target = windows_target();
    let mut command = Command::new(cargo());
    command
        .current_dir(root)
        .args([
            "build",
            "-p",
            "kagisecure-ffi",
            "--features",
            "capi",
            "--target",
        ])
        .arg(target);
    if profile == Profile::Release {
        command
            .arg("--release")
            .env("RUSTFLAGS", release_rustflags(root));
    }
    run(&mut command).context("building kagisecure-ffi with the capi feature")?;

    let built = root
        .join("target")
        .join(target)
        .join(profile.cargo_dir())
        .join(DLL);
    if !built.is_file() {
        bail!("cargo did not produce {}", built.display());
    }
    let staging = staging_dir(root, profile);
    std::fs::create_dir_all(&staging).with_context(|| format!("creating {}", staging.display()))?;
    let destination = staging.join(DLL);
    std::fs::copy(&built, &destination)
        .with_context(|| format!("staging {}", destination.display()))?;

    println!("bindgen-cs: {DLL} -> {}", destination.display());
    Ok(destination)
}

/// Run csbindgen over [`SOURCES`] into `output`.
fn generate(root: &Path, output: &Path) -> Result<()> {
    let mut builder = csbindgen::Builder::default();
    for source in SOURCES {
        builder = builder.input_extern_file(root.join(source));
    }
    builder
        // Only the C ABI: anything else csbindgen might find is not exported.
        .method_filter(|name| name.starts_with("kgs_"))
        // The tag enums are never an argument or a field type (a value C# made up must be an
        // error, not undefined behaviour), so nothing reaches them; name them explicitly so the
        // public C# enums can take their values from the generated ones.
        .always_included_types(tag_enums(root)?)
        .csharp_dll_name("kagisecure_ffi")
        .csharp_class_name("NativeMethods")
        .csharp_namespace("Kagisecure.Interop.Native")
        .csharp_class_accessibility("internal")
        // One callback crosses this ABI — the presence gate's `confirm`, called synchronously on
        // the thread that asked for a release (capi/presence.rs says why that is the narrowest
        // exception to ADR-0003's "no foreign callbacks"). As a `delegate* unmanaged[Cdecl]`
        // function pointer, not a marshalled delegate: the assembly disables runtime marshalling
        // (Native/Abi.cs), under which a delegate parameter is not allowed at all, and an
        // `[UnmanagedCallersOnly]` static method needs no delegate kept alive against the GC.
        .csharp_use_function_pointer(true)
        .csharp_generate_const_filter(|name| name == "KGS_ABI_VERSION")
        .csharp_file_header(HEADER)
        .generate_csharp_file(output)
        .map_err(|e| anyhow::anyhow!("csbindgen: {e}"))
        .with_context(|| format!("generating {}", output.display()))
}

/// Every `pub enum` in `capi/enums.rs`.
fn tag_enums(root: &Path) -> Result<Vec<String>> {
    let path = root.join("crates/kagisecure-ffi/src/capi/enums.rs");
    let source =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    Ok(source
        .lines()
        .filter_map(|line| line.strip_prefix("pub enum "))
        .filter_map(|rest| rest.split_whitespace().next())
        .map(str::to_owned)
        .collect())
}

/// This machine's Windows target triple. `pub(crate)` so `dist_windows` builds the helper
/// binaries for the same target this builds `kagisecure_ffi.dll` for.
pub(crate) fn windows_target() -> &'static str {
    if cfg!(target_arch = "aarch64") {
        "aarch64-pc-windows-msvc"
    } else {
        "x86_64-pc-windows-msvc"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::util::repo_root;

    /// Generate into a scratch file and read it back, line endings normalized — git may check
    /// the committed file out with CRLF.
    fn generate_fresh(root: &Path, name: &str) -> String {
        let scratch = std::env::temp_dir().join(format!(
            "kagisecure-bindgen-cs-{}-{name}.g.cs",
            std::process::id()
        ));
        generate(root, &scratch).expect("csbindgen runs");
        let text = std::fs::read_to_string(&scratch).expect("read the generated file");
        let _ = std::fs::remove_file(&scratch);
        text.replace("\r\n", "\n")
    }

    /// The drift check ADR-0009 gives the Swift bindings, applied to the C#: a `capi` signature or
    /// layout that changed without `cargo xtask bindgen-cs` being run fails here, rather than
    /// passing the wrong bytes across the boundary at run time.
    #[test]
    fn generated_csharp_is_up_to_date() {
        let root = repo_root().unwrap();
        let fresh = generate_fresh(&root, "check");
        let committed = std::fs::read_to_string(root.join(GENERATED))
            .expect("the generated C# is checked in")
            .replace("\r\n", "\n");
        assert!(
            fresh == committed,
            "{GENERATED} is stale: run `cargo xtask bindgen-cs` and commit the result"
        );
    }

    #[test]
    fn generation_is_idempotent() {
        let root = repo_root().unwrap();
        assert_eq!(
            generate_fresh(&root, "first"),
            generate_fresh(&root, "second")
        );
    }

    #[test]
    fn every_export_and_every_tag_enum_is_declared() {
        let root = repo_root().unwrap();
        let generated = generate_fresh(&root, "coverage");
        let mut exports = 0;
        for source in SOURCES {
            let text = std::fs::read_to_string(root.join(source)).unwrap();
            let mut lines = text.lines();
            while let Some(line) = lines.next() {
                if line.trim() != "#[unsafe(no_mangle)]" {
                    continue;
                }
                let signature = lines.next().expect("a function follows no_mangle");
                let name = signature
                    .split("fn ")
                    .nth(1)
                    .and_then(|rest| rest.split('(').next())
                    .expect("an extern fn");
                exports += 1;
                assert!(
                    generated.contains(&format!("EntryPoint = \"{name}\"")),
                    "{name} is exported but not declared in C#"
                );
            }
        }
        assert!(
            exports > 100,
            "only {exports} exports found; the scan is broken"
        );
        for name in tag_enums(&root).unwrap() {
            assert!(
                generated.contains(&format!("enum {name} : uint")),
                "{name} is not generated"
            );
        }
        assert!(generated.contains("KGS_ABI_VERSION"));
    }
}
