//! Generate `packaging/windows/License.rtf` for the MSI's license dialog, from the two license
//! files the repository already carries at its root.
//!
//! kagisecure is dual-licensed (`LICENSE-MIT` and `LICENSE-APACHE`, matching the standard Rust
//! ecosystem convention); the installer's `LicenseAgreementDlg` (WiX UI extension,
//! `packaging/windows/Product.wxs`) needs one RTF file to show, so this concatenates both license
//! texts into one document rather than picking one and silently dropping the other. Regenerated by
//! `dist_windows.rs` on every `cargo xtask dist-windows` run — not checked in — so the installer
//! never shows stale license text if `LICENSE-MIT`/`LICENSE-APACHE` ever change and nobody remembers
//! to regenerate a committed copy.

use std::path::Path;

use anyhow::{Context, Result};

/// A plain-text separator between the two license bodies, escaped like everything else.
const SEPARATOR: &str = "--------------------------------------------------------------------";

/// Build the RTF document from `LICENSE-MIT` and `LICENSE-APACHE` at the repository root.
pub fn generate(root: &Path) -> Result<String> {
    let mit = read_license(root, "LICENSE-MIT")?;
    let apache = read_license(root, "LICENSE-APACHE")?;
    Ok(render(&mit, &apache))
}

/// Generate and write the RTF to `dest` (`packaging/windows/License.rtf` in practice).
pub fn write(root: &Path, dest: &Path) -> Result<()> {
    let rtf = generate(root)?;
    std::fs::write(dest, rtf).with_context(|| format!("writing {}", dest.display()))?;
    println!("dist-windows: license -> {}", dest.display());
    Ok(())
}

fn read_license(root: &Path, name: &str) -> Result<String> {
    let path = root.join(name);
    std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))
}

/// Assemble the RTF: a one-line preamble explaining the dual license, then the MIT text, a
/// separator, then the Apache text. Each license file already opens with its own title line
/// ("MIT License", "Apache License / Version 2.0 / ..."), so nothing here repeats a heading.
fn render(mit: &str, apache: &str) -> String {
    let mut body = String::new();
    body.push_str(&escape(
        "kagisecure is dual-licensed under your choice of either of the following two licenses.",
    ));
    body.push_str("\\par\\par\n");
    body.push_str(&paragraphs_to_rtf(mit));
    body.push_str("\\par\\par\n");
    body.push_str(&escape(SEPARATOR));
    body.push_str("\\par\\par\n");
    body.push_str(&paragraphs_to_rtf(apache));

    format!(
        "{{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1033\n\
         {{\\fonttbl{{\\f0\\fswiss\\fcharset0 Segoe UI;}}}}\n\
         \\viewkind4\\uc1\\pard\\f0\\fs18\n\
         {body}\n\
         }}"
    )
}

/// Reflow `text` into RTF paragraphs: a run of non-blank lines becomes one paragraph (wrapped
/// lines joined with a space, so the license's own ~80-column hard-wrapping does not turn into a
/// hard line break every line); a blank line starts a new paragraph. Matches how both
/// `LICENSE-MIT` and `LICENSE-APACHE` are actually laid out — short blank-line-delimited clauses,
/// not one giant block — so this does not collapse the whole document into a single paragraph.
fn paragraphs_to_rtf(text: &str) -> String {
    let mut paragraphs: Vec<String> = Vec::new();
    let mut current: Vec<&str> = Vec::new();
    for line in text.lines() {
        if line.trim().is_empty() {
            if !current.is_empty() {
                paragraphs.push(current.join(" "));
                current.clear();
            }
        } else {
            current.push(line.trim());
        }
    }
    if !current.is_empty() {
        paragraphs.push(current.join(" "));
    }
    paragraphs
        .iter()
        .map(|p| escape(p))
        .collect::<Vec<_>>()
        .join("\\par\\par\n")
}

/// Escape one line of plain text for RTF: backslash and braces are the control characters RTF
/// itself uses, and anything outside ASCII needs `\uNNNN` plus a `?` fallback glyph for readers
/// that do not understand Unicode escapes. `LICENSE-MIT`/`LICENSE-APACHE` are pure ASCII today
/// (checked when this was written), so the `\u` path is defensive, not exercised by the committed
/// license files — covered instead by a synthetic string in the tests below.
fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            '\t' => out.push_str("\\tab "),
            c if c.is_ascii() && !c.is_control() => out.push(c),
            c if c == '\n' || c == '\r' => {} // handled by the paragraph splitter, not per-char
            c => out.push_str(&format!("\\u{}?", c as u32)),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::util::repo_root;

    #[test]
    fn generated_rtf_is_well_formed_and_has_both_licenses() {
        let root = repo_root().unwrap();
        let rtf = generate(&root).expect("both LICENSE files are present");

        assert!(rtf.starts_with("{\\rtf1"), "not an RTF document: {rtf:.80}");
        assert!(rtf.trim_end().ends_with('}'), "RTF document not closed");

        let opens = rtf.matches('{').count();
        let closes = rtf.matches('}').count();
        assert_eq!(
            opens, closes,
            "unbalanced RTF braces ({opens} open, {closes} close)"
        );

        assert!(rtf.contains("MIT License"), "MIT license text missing");
        assert!(
            rtf.contains("Apache License"),
            "Apache license text missing"
        );
        assert!(
            rtf.contains("dual-licensed"),
            "missing the explanatory preamble"
        );
    }

    #[test]
    fn generation_is_deterministic() {
        let root = repo_root().unwrap();
        assert_eq!(generate(&root).unwrap(), generate(&root).unwrap());
    }

    #[test]
    fn escapes_rtf_control_characters() {
        assert_eq!(escape(r"back\slash"), r"back\\slash");
        assert_eq!(escape("brace{d}"), r"brace\{d\}");
        assert_eq!(escape("a\tb"), r"a\tab b");
    }

    #[test]
    fn escapes_non_ascii_as_unicode_runs() {
        // Not present in the committed license files today, but the escaper still has to cope if
        // either file ever gains a non-ASCII character (a curly quote, an em dash, a name).
        assert_eq!(escape("caf\u{e9}"), "caf\\u233?");
    }

    #[test]
    fn blank_lines_start_new_paragraphs_wrapped_lines_join() {
        let text = "one\ntwo\n\nthree";
        let rtf = paragraphs_to_rtf(text);
        assert_eq!(rtf, "one two\\par\\par\nthree");
    }
}
